import { Metadata } from "next";
import AppLayout from "../components/AppLayout";
import styles from "./globals.css";

export const metadata: Metadata = {
  title: "zhwdailysummarizer",
  description: "Generated by Zapier's nextjs-template",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={styles.html}>
      <head>
        <link
          color="#FF4A00"
          href="https://cdn.zapier.com/zapier/images/logo_zapier_black.svg"
          rel="mask-icon"
        />
        <link
          href="https://cdn.zapier.com/zapier/images/favicon.ico"
          rel="icon"
          type="image/x-icon"
        />

        {/* Style reset for user agent stylesheet */}
        <style>{`body { margin: 0; background: var(--zds-colors-neutral-100);}`}</style>
      </head>

      <body className={styles.body}>
        {/*
            This AppLayout component will render for all routes in the application.
            If you have a subroute that does not need the UniversalLayout,
            this <AppLayout> component should be rendered in a subroute's layout.tsx file.
          */}
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
