default_context:

  gitlab_repo: zhwdailysummarizer
  project_name: zhwdailysummarizer
  project_slug: zhwdailysummarizer
  project_description: Zapier Hack Week - May 12 - 16

  responsible_team: 

  service_tag: team-enterprise-experience
  service_tier: 4

  local_port: 9955

  owner_opslevel: enterprise_experience
  lifecycle_opslevel: generally_available
